
INSERT INTO `ProgramsRequirement` (`Name`, `Subject`, `CourseNumber`, `YearRequirement`) VALUES
('Biomedical and Electrical Engineering', 'BIOL', 1003, 0),
('Biomedical and Electrical Engineering', 'CHEM', 1001, 0),
('Biomedical and Electrical Engineering', 'ECOR', 1010, 0),
('Biomedical and Electrical Engineering', 'MATH', 1004, 0),
('Biomedical and Electrical Engineering', 'MATH', 1104, 0),
('Biomedical and Electrical Engineering', 'CHEM', 1002, 1),
('Biomedical and Electrical Engineering', 'ECOR', 1101, 1),
('Biomedical and Electrical Engineering', 'ECOR', 1606, 1),
('Biomedical and Electrical Engineering', 'MATH', 1005, 1),
('Biomedical and Electrical Engineering', 'PHYS', 1004, 1),
('Biomedical and Electrical Engineering', 'ECOR', 2606, 2),
('Biomedical and Electrical Engineering', 'ELEC', 2501, 2),
('Biomedical and Electrical Engineering', 'MATH', 2004, 2),
('Biomedical and Electrical Engineering', 'SYSC', 2006, 2),
('Biomedical and Electrical Engineering', 'CCDP', 2100, 3),
('Biomedical and Electrical Engineering', 'ELEC', 2507, 3),
('Biomedical and Electrical Engineering', 'ELEC', 2607, 3),
('Biomedical and Electrical Engineering', 'ELEC', 3105, 3),
('Biomedical and Electrical Engineering', 'MATH', 3705, 3),
('Biomedical and Electrical Engineering', 'ELEC', 3908, 4),
('Biomedical and Electrical Engineering', 'SYSC', 3006, 4),
('Biomedical and Electrical Engineering', 'SYSC', 3203, 4),
('Biomedical and Electrical Engineering', 'SYSC', 3610, 4),
('Biomedical and Electrical Engineering', 'ELEC', 3500, 5),
('Biomedical and Electrical Engineering', 'ELEC', 3909, 5),
('Biomedical and Electrical Engineering', 'STAT', 3502, 5),
('Biomedical and Electrical Engineering', 'SYSC', 3501, 5),
('Biomedical and Electrical Engineering', 'SYSC', 4201, 5),
('Biomedical and Electrical Engineering', 'ECOR', 3800, 6),
('Biomedical and Electrical Engineering', 'ELEC', 4601, 6),
('Biomedical and Electrical Engineering', 'SYSC', 4405, 6),
('Biomedical and Electrical Engineering', 'SYSC', 4203, 6),
('Biomedical and Electrical Engineering', 'SYSC', 4917, 6),
('Biomedical and Electrical Engineering', 'ECOR', 4995, 7),
('Computer Systems Engineering', 'ECOR', 1010, 0),
('Computer Systems Engineering', 'MATH', 1004, 0),
('Computer Systems Engineering', 'MATH', 1104, 0),
('Computer Systems Engineering', 'PHYS', 1003, 0),
('Computer Systems Engineering', 'SYSC', 1005, 0),
('Computer Systems Engineering', 'CHEM', 1101, 1),
('Computer Systems Engineering', 'ECOR', 1101, 1),
('Computer Systems Engineering', 'MATH', 1005, 1),
('Computer Systems Engineering', 'PHYS', 1004, 1),
('Computer Systems Engineering', 'SYSC', 2006, 1),
('Computer Systems Engineering', 'CCDP', 2100, 2),
('Computer Systems Engineering', 'ELEC', 2501, 2),
('Computer Systems Engineering', 'MATH', 2004, 2),
('Computer Systems Engineering', 'SYSC', 2001, 2),
('Computer Systems Engineering', 'SYSC', 2004, 2),
('Computer Systems Engineering', 'ELEC', 2507, 3),
('Computer Systems Engineering', 'ELEC', 2607, 3),
('Computer Systems Engineering', 'MATH', 3705, 3),
('Computer Systems Engineering', 'SYSC', 2003, 3),
('Computer Systems Engineering', 'SYSC', 2100, 3),
('Computer Systems Engineering', 'ECOR', 3800, 4),
('Computer Systems Engineering', 'ELEC', 3500, 4),
('Computer Systems Engineering', 'SYSC', 3600, 4),
('Computer Systems Engineering', 'SYSC', 4001, 4),
('Computer Systems Engineering', 'SYSC', 3010, 4),
('Computer Systems Engineering', 'STAT', 3502, 5),
('Computer Systems Engineering', 'SYSC', 3501, 5),
('Computer Systems Engineering', 'SYSC', 3601, 5),
('Computer Systems Engineering', 'SYSC', 3303, 5),
('Computer Systems Engineering', 'SYSC', 3020, 5),
('Computer Systems Engineering', 'ELEC', 4705, 6),
('Computer Systems Engineering', 'SYSC', 4602, 6),
('Computer Systems Engineering', 'SYSC', 4907, 6),
('Computer Systems Engineering', 'ECOR', 4995, 7),
('Computer Systems Engineering', 'SYSC', 4507, 7),
('Computer Systems Engineering', 'SYSC', 4805, 7),
('Software Engineering', 'ECOR', 1010, 0),
('Software Engineering', 'MATH', 1004, 0),
('Software Engineering', 'MATH', 1101, 0),
('Software Engineering', 'PHYS', 1003, 0),
('Software Engineering', 'SYSC', 1005, 0),
('Software Engineering', 'CHEM', 1101, 1),
('Software Engineering', 'ECOR', 1101, 1),
('Software Engineering', 'MATH', 1005, 1),
('Software Engineering', 'PHYS', 1004, 1),
('Software Engineering', 'SYSC', 2006, 1),
('Software Engineering', 'CCDP', 2100, 2),
('Software Engineering', 'ELEC', 2501, 2),
('Software Engineering', 'MATH', 2004, 2),
('Software Engineering', 'SYSC', 2001, 2),
('Software Engineering', 'SYSC', 2004, 2),
('Software Engineering', 'ELEC', 2607, 3),
('Software Engineering', 'MATH', 1805, 3),
('Software Engineering', 'SYSC', 2003, 3),
('Software Engineering', 'SYSC', 2100, 3),
('Software Engineering', 'ECOR', 3800, 4),
('Software Engineering', 'COMP', 3005, 4),
('Software Engineering', 'SYSC', 4001, 4),
('Software Engineering', 'SYSC', 3110, 4),
('Software Engineering', 'STAT', 3502, 5),
('Software Engineering', 'SYSC', 3303, 5),
('Software Engineering', 'SYSC', 3101, 5),
('Software Engineering', 'SYSC', 3120, 5),
('Software Engineering', 'SYSC', 4106, 5),
('Software Engineering', 'ELEC', 4507, 6),
('Software Engineering', 'SYSC', 4101, 6),
('Software Engineering', 'SYSC', 4120, 6),
('Software Engineering', 'SYSC', 4927, 6),
('Software Engineering', 'SYSC', 4005, 7),
('Software Engineering', 'SYSC', 4507, 7),
('Software Engineering', 'ECOR', 4995, 7),
('Software Engineering', 'SYSC', 4806, 7);
