<?php 
	$pageTitle = "Timetable";
	require("../resources/config.php");
	include(TEMPLATES_PATH . "/header.php");
?>

<div id="timetable">
	<!-- generated by JavaScript -->
</div>

<div id="sidebar">
	<div id="inner-sb">
		\\ SIDEBAR OPTION MENU //
	</div>
</div>



<?php include(TEMPLATES_PATH . "/footer.php"); ?>