<?php 
	$pageTitle = "Timetable";
	require("../resources/config.php");
	include(TEMPLATES_PATH . "/header.php");
	session_start();
	// TODO: handle php stuff from dbConnection
	// TODO: if no sessions, return to index page
	if (isset($_SESSION['timetables'])) {
		$generatedTables = $_SESSION['timetables'];
	}
?>

<div id="timetable">
	<!-- generated by JavaScript -->
</div>

<div id="sidebar-wrapper">
	<div id='registration' onclick="todo()">Click to Register</div>
	<div id='selected-courses-header'>Selected Courses:</div>
	<div id='selected-courses'></div>
	<div id='add-elective'>Click to Add Electives</div>
	<div id='add-course'>Click to 	Add Courses</div>
	<div id='alt-table-header'>Select Alternate Table:</div>
	<div id="alt-table">
		<!-- generated by JavaScript -->
	</div>

</div>



<?php include(TEMPLATES_PATH . "/footer.php"); ?>
